/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.sociotorcedor;

import java.util.List;
import java.util.stream.Collectors;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Ingressos extends javax.swing.JFrame {

    List<Produto> prods;
    List<FormaPgto> formas;
    /**
     * Creates new form TiposIngressos
     */
    public Ingressos() {
        initComponents();
          carregaProdutos();
    }
    public void carregaProdutos() {
        try {
            prods = Produto.buscaProdutos();
        
            if (prods.size() > 0) {
                ImageIcon img1 = new ImageIcon(prods.get(0).getImagem());
                lblImg1.setIcon(img1);
                lblAssento1.setText("Assento " + prods.get(0).getAssento());
                lblCod1.setText(String.valueOf(prods.get(0).getId()));
                lblDescr1.setText(prods.get(0).getDescr());
                lblPreco1.setText("R$ " + prods.get(0).getPreco());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            System.exit(-1);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblImg1 = new javax.swing.JLabel();
        lblCod1 = new javax.swing.JLabel();
        lblDescr1 = new javax.swing.JLabel();
        lblPreco1 = new javax.swing.JLabel();
        lblAssento1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        edtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblProdSel = new javax.swing.JLabel();
        btnComprar = new javax.swing.JButton();
        btnAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Produtos\n"));

        lblImg1.setText("lblimg1");

        lblCod1.setText("lblCod1");

        lblDescr1.setText("lblDescri1");

        lblPreco1.setText("lblPreco1");

        lblAssento1.setText("lblAssento1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImg1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPreco1)
                    .addComponent(lblDescr1)
                    .addComponent(lblCod1)
                    .addComponent(lblAssento1))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(lblImg1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblAssento1)
                .addGap(18, 18, 18)
                .addComponent(lblCod1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDescr1)
                .addGap(18, 18, 18)
                .addComponent(lblPreco1)
                .addGap(26, 26, 26))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Menu de opções\n"));

        edtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtCodigoActionPerformed(evt);
            }
        });
        edtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                edtCodigoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edtCodigoKeyTyped(evt);
            }
        });

        jLabel2.setText("Digite o codigo");

        lblProdSel.setText("lblProdSel");

        btnComprar.setText("Confirmar compra");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });

        btnAdmin.setText("Gerenciar");
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2)
            .addComponent(lblProdSel)
            .addComponent(edtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnComprar)
            .addComponent(btnAdmin)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblProdSel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnComprar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAdmin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 150, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtCodigoActionPerformed

    private void edtCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtCodigoKeyReleased
        String cod = edtCodigo.getText();
        String descr = "";

        if (cod.length() > 0) {
            Integer codProd = Integer.parseInt(cod);

            for (Produto p : prods) {
                if (p.getId() == codProd) {
                    descr = p.getDescr();
                }
            }
        }
        lblProdSel.setText(descr);
    }//GEN-LAST:event_edtCodigoKeyReleased

    private void edtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtCodigoKeyTyped
        char key = evt.getKeyChar();

        if(key < 48 || key > 57){
            evt.consume();
        }
    }//GEN-LAST:event_edtCodigoKeyTyped

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        String codProd = edtCodigo.getText();
        Integer cod = -1;
        Object sel;
        Produto prod = null;
        FormaPgto forma = null;

        if (codProd.length() > 0) {
            cod = Integer.parseInt(codProd);
        } else {
            JOptionPane.showMessageDialog(this, "Você deve informar um Produto");
            return;
        }

        for (Produto p : prods) {
            if (p.getId() == cod) {
                prod = p;
            }
        }

        if (prod == null) {
            JOptionPane.showMessageDialog(this, "Produto inválido!");
            return;
        }

        try {
            formas = FormaPgto.buscaFormasPgto();
            Object[] opcoes = formas.stream().map(f -> f.getDescr())
            .collect(Collectors.toList()).toArray();
            sel = JOptionPane.showInputDialog(this,
                "Selecione a Forma de Pagamento...", "Formas de Pagamento",
                JOptionPane.QUESTION_MESSAGE, null,
                opcoes, opcoes[0]);
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
            return;
        }

        for (FormaPgto f : formas) {
            if (f.getDescr().equals(sel)) {
                forma = f;
            }
        }

        if (forma != null) {
            Venda reg = new Venda(prod, forma);
            try {
                reg.salvar();
            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this,
                    ex.getMessage());
                return;
            }

            JOptionPane.showMessageDialog(this,
                "Venda confirmada! Retire seu produto.");
        }
        else {
            JOptionPane.showMessageDialog(this,
                "Você deve informar uma Forma de Pagamento!");
        }

    }//GEN-LAST:event_btnComprarActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        TelaAdmin adm = new TelaAdmin();
        adm.setVisible(true);
    }//GEN-LAST:event_btnAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingressos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingressos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingressos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingressos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingressos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnComprar;
    private javax.swing.JTextField edtCodigo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAssento1;
    private javax.swing.JLabel lblCod1;
    private javax.swing.JLabel lblDescr1;
    private javax.swing.JLabel lblImg1;
    private javax.swing.JLabel lblPreco1;
    private javax.swing.JLabel lblProdSel;
    // End of variables declaration//GEN-END:variables
}
